### PR TITLE
Hide the loading indicator after image load.

### PR DESCRIPTION
**Pull request by paulstraw**
This is particularly important for semi-transparent images.

### CODE REVIEW

**Comment by paulstraw** [comment]
Hey @muybien, as discussed last night in the imgix Community Slack, I've made a change that hides the loading indicator after the image has fully loaded in. I'm going to release it as 0.3.3 shortly.

**Comment by MuyBien** [comment]
Youhou ! Perfect ! But in Firefox there is another problem. I will open an issue. Thanks for this one ;)

**Comment by paulstraw** [comment]
Oh no! Well, thanks for reporting this one. Happy to track down the FF one whenever you open it! ^_^

**Comment by MuyBien** [comment]
Thanks for your reactivity. For the FF one I just opened it. I don't think it will be hard to fix :)

**Pull request merged**
