### PR TITLE
feat(mobile): add touch delay to allow scroll on mobile

### LINKED ISSUE #77: Introduce a delay to allow scroll on mobile
Thanks for this awesome library, looked awesome and very easy to customize!

I'm encountering a small issue though: I have an image that takes nearly all the screen estate on mobile. The zoom on mobile looks good and works well, but the issue is that I simply can't scroll at all as the touch event is immediately captured to launch the zoom.

Would it be possible to add some smarter detection so that the zoom is only started after a few milli seconds of hold? I've tried the "hoverDelay" but it does not seem to handle this use case.

Thanks :)

### PR DESCRIPTION
**Pull request by begner**
# Description
This is a fix for touch capable devices, there drift zoom prevents scrolling while displayed on screen. The Drift Stage cant be use for start oft gestures, because the event will always be 
default-prevented. Its not breaking because you need to set touchDelay (> 0) for this to work. IF there is touchdelay set, drift only prevents browsers default behaviour if the zoom is active. otherwise the events will pass.  Fixes #77

# Bug Fix
- [x] All existing unit tests are still passing (if applicable)
- [x] Add some [steps](#steps-to-test) so we can test your bug fix
- [x] Update the readme

# Steps to Test:
- Create an (large) image which has drift zoom applied on.
- Configure drift with no touchDelay.
- Add some "lorem ipsum" text below.
- Use a touch capable mobile (iphone X here)
- open the page on a mobile an make sure the image covers the complete display
- try to scroll down
You cant!

With fix:
- set touchDelay to 500
- try to scroll down (while gesture starts on the image)
You can scroll now!

- holding you finger on the image on the image for > 500ms
now you can move around the zoom maginfication bubble without scrolling

### CODE REVIEW

**Comment by begner** [comment]
Hm - the tests wont run on windows - so i cant test it locally. Anyway it ist strange - because the touchDelay parameter is passed and should be present.

> Uncaught TypeError: Cannot read property 'touchDelay' of undefined thrown

**Comment by begner** [comment]
> do you happen to have something like a public codepen demo I can use to try this out myself? 

Sure

Visit with your mobile and try to scroll down.

Thats the issue:
https://codepen.io/begner/full/vYBZJJB
It instantly does inpane-zooming. No scrolling possible

Thats with the fix:
https://codepen.io/begner/full/PoYjKyb
You can scroll. If you touch and dont move your finger for a small amount of time, the zoom will kick in (while its visible. you wont scroll when moving your finger around)

**Comment by begner** [comment]
> uncommit the `dist/` files? 
Done - was a mistake, should have been in a branch. :D

**Comment by sherwinski** [comment]
@begner no problem and thanks!
Out of curiosity, do you think there's someway we can add a test case for this to make sure future work doesn't break it?

**Comment by begner** [comment]
> Out of curiosity, do you think there's someway we can add a test case for this to make sure future work doesn't break it?

As long as the used headless-test-browsers does not support REAL mobile behaviours (with real touchevents): no.

**Comment by sherwinski** [comment]
Fair enough, besides that I think this PR is good to go. Thanks for putting in the time to address my feedback @begner

**Comment by begner** [comment]
@sherwinski 
Thanks for your time, too.

Can you drop me a note, when the npm version is released?

**Comment by sherwinski** [comment]
@begner 
Will do, I just need to finish fixing one other bug so I can release them together. I am aiming to have it done in the next few days.

**Comment by sherwinski** [comment]
Great news @begner, this feature is now released as part of [Drift v1.4.0](https://www.npmjs.com/package/drift-zoom/v/1.4.0) 🎉

**Comment by begner** [comment]
> released as part of [Drift v1.4.0]

👍

**Pull request merged**
