### PR TITLE
Fix bounding box positioning on scrolled documents by adding the element to the document body by default

### PR DESCRIPTION
**Pull request by whefter**
When the document is scrolled, the bounding box positioning is bogus.

This is because determining the position of the bounding box is done using getBoundingClientRect(), but the box is added to the master element's offset parent. The determined scroll offset then breaks positioning. The positioning cannot be fixed by CSS alone.

Introducing a parameter "boundingBoxContainer", set to document.body by default, fixes this issue without any need to touch the positioning computation logic.

### CODE REVIEW

**Comment by toregua** [comment]
Please merge !

**Comment by markadrake** [comment]
Second that. Please merge this.

**Comment by frederickfogerty** [comment]
Hey @whefter 👋 

Fred here from Imgix. From today I'm responsible for the maintenance of this repo. Thanks for the PR!

I'm hesitant to fundamentally change how the positioning works - do you know if there are any situations where this wouldn't work? e.g. in what situations would you expect users to use `boundingBoxContainer`?

**Comment by whefter** [comment]
As I explained in my original post, the need for this change arises as soon as a document containing an active Drift is scrolled.

Perhaps this was due to our Drift object being nested (and not a direct child of body), but I imagine this would be the case for most use cases.

It's been over a year and I can't remember the exact issue, but to the best of my recollection, the boundingBoxContainer needs to be document.body because getBoundingClientRect() returns values that are _always_ relative to the viewport (i.e. document.body), but the bounding box that Drift inserts is appended to the element's offset parent, introducing an offset in the positioning. I can't see in what situation this would not be an issue.

Sorry about the changes to the dist/ files, will revert.

**Comment by frederickfogerty** [comment]
Great, thanks for the explanation @whefter. I'll merge this now.

**Pull request merged**
