### PR TITLE
`noop` animation fix

### PR DESCRIPTION
**Pull request by paulstraw**
See #21 for details

### CODE REVIEW

**Comment by paulstraw** [comment]
Hey @aghouseh, can you give this a go to verify that it's all fixed for you? Seems to be working on my end.

**Comment by paulstraw** [comment]
(Tested in Safari 9.1 and IE 11)

**Comment by aghouseh** [comment]
Working perfect for me now; thanks a bunch for the speedy fix.

**Comment by paulstraw** [comment]
Rad. No problem. I'll get this merged with a version bump shortly!

**Pull request merged**
